import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "@/components/Navbar";
import Work from "@/components/Content/Work";
import Hero from "@/components/Content";
import About from "@/components/Content/About";

const Home: NextPage = () => {
  return (
    <>
      <main>
        <Head>
          <title>@mrshanas|Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <header className="relative">
          <Navbar />
        </header>
        <section>
          <Hero />
          <About />
          <Work/>
          {/* {works.map(({ description, url, image }, i) => (
            <Work description={description} url={url} image={image} key={i} />
          ))} */}
          
        </section>
      </main>
      <footer></footer>
    </>
  );
};

export default Home;
