import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "@/components/Navbar";
import Hero from "@/components/Content";
import About from "@/components/Content/About";
import Skills from "@/components/Content/Skills";
import Works from "@/components/Content/Works";

const Home: NextPage = () => {
  return (
    <>
      <main>
        <Head>
          <title>@mrshanas|Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <header className="relative">
          <Navbar />
        </header>
        <section>
          <Hero />
          <About />
          <Works />
          <Skills />
        </section>
      </main>
      <footer></footer>
    </>
  );
};

export default Home;
